import { Construct } from "constructs";
import { AzAPIBase, IAzAPIBaseProps } from "./core-azapi";

/**
 * Interface representing the properties for instance pool configuration.
 *
 * @extends IAzAPIBaseProps Base properties including name, location, and tags.
 */
export interface DashboardGrafanaProps extends IAzAPIBaseProps {

}

/**
 * DashboardGrafana resource
 */
export class DashboardGrafana extends AzAPIBase {
  constructor(scope: Construct, id: string, props: DashboardGrafanaProps) {
    super(scope, id, props);
  }

  protected getResourceType(): string {
    return "Microsoft.Dashboard/grafana@2022-08-01";
  }

  protected getResourceBody(props: DashboardGrafanaProps): string {
    return JSON.stringify(
        {properties: {apiKey: "string", autoGeneratedDomainNameLabelScope: "TenantReuse", deterministicOutboundIP: "string", grafanaIntegrations: {azureMonitorWorkspaceIntegrations: [{azureMonitorWorkspaceResourceId: "string"}]}, publicNetworkAccess: "string", zoneRedundancy: "string"}, sku: {name: "string"}}
    );
  }
}
