import { Construct } from "constructs";
import { AzAPIBase, IAzAPIBaseProps } from "./core-azapi";

export interface DashboardGrafanaProps extends IAzAPIBaseProps {

}

export class DashboardGrafana extends AzAPIBase {
  constructor(scope: Construct, id: string, props: DashboardGrafanaProps) {
    super(scope, id, props);
  }

  protected getResourceType(): string {
    return "Microsoft.Dashboard/grafana@2022-08-01";
  }

  protected getResourceBody(props: DashboardGrafanaProps): string {
    return JSON.stringify(
      {properties: {apiKey: "string", autoGeneratedDomainNameLabelScope: "TenantReuse", deterministicOutboundIP: "string", grafanaIntegrations: {azureMonitorWorkspaceIntegrations: [{azureMonitorWorkspaceResourceId: "string"}]}, publicNetworkAccess: "string", zoneRedundancy: "string"}, sku: {name: "string"}}
    );
  }
}

// | Name | Description | Value |
// |-|-|-|
// | name | The resource name | string (required) |
// | location | The geo-location where the grafana resource lives | string |
// | tags | The tags for grafana resource. | Dictionary of tag names and values. SeeTags in templates |
// | sku | The Sku of the grafana resource. | ResourceSku |
// | identity | The managed identity of the grafana resource. | ManagedServiceIdentity |
// | properties | Properties specific to the grafana resource. | ManagedGrafanaProperties |

// | Name | Description | Value |
// |-|-|-|
// | type | Type of managed service identity (where both SystemAssigned and UserAssigned types are allowed). | 'None''SystemAssigned''SystemAssigned,UserAssigned''UserAssigned' (required) |
// | userAssignedIdentities | The set of user assigned identities associated with the resource. The userAssignedIdentities dictionary keys will be ARM resource ids in the form: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}. The dictionary values can be empty objects ({}) in requests. | object |

// | Name | Description | Value |
// |-|-|-|
// | apiKey | The api key setting of the Grafana instance. | 'Disabled''Enabled' |
// | autoGeneratedDomainNameLabelScope | Scope for dns deterministic name hash calculation. | 'TenantReuse' |
// | deterministicOutboundIP | Whether a Grafana instance uses deterministic outbound IPs. | 'Disabled''Enabled' |
// | grafanaIntegrations | GrafanaIntegrations is a bundled observability experience (e.g. pre-configured data source, tailored Grafana dashboards, alerting defaults) for common monitoring scenarios. | GrafanaIntegrations |
// | publicNetworkAccess | Indicate the state for enable or disable traffic over the public interface. | 'Disabled''Enabled' |
// | zoneRedundancy | The zone redundancy setting of the Grafana instance. | 'Disabled''Enabled' |

// | Name | Description | Value |
// |-|-|-|
// | azureMonitorWorkspaceIntegrations |  | AzureMonitorWorkspaceIntegration[] |

// | Name | Description | Value |
// |-|-|-|
// | azureMonitorWorkspaceResourceId | The resource Id of the connected Azure Monitor Workspace. | string |

// | Name | Description | Value |
// |-|-|-|
// | name |  | string (required) |
