import { Construct } from "constructs";
import { Fn } from "cdktf";
/*
 * Provider bindings are generated by running `cdktf get`.
 * See https://cdk.tf/provider-generation for more details.
 */
import { Resource } from "./.gen/providers/azapi/resource";
class MyConvertedCode extends Construct {
  constructor(scope: Construct, name: string) {
    super(scope, name);
    /*The following providers are missing schema information and might need manual adjustments to synthesize correctly: azapi.
    For a more precise conversion please use the --provider flag in convert.*/
    new Resource(this, "symbolicname", {
      body: Fn.jsonencode({
        properties: {
          licenseType: "string",
          subnetId: "string",
          vCores: int,
        },
        sku: {
          capacity: int,
          family: "string",
          name: "string",
          size: "string",
          tier: "string",
        },
      }),
      location: "string",
      name: "string",
      parent_id: "string",
      tags: {
        tagName1: "tagValue1",
        tagName2: "tagValue2",
      },
      type: "Microsoft.Sql/instancePools@2022-05-01-preview",
    });
  }
}


/**
 * Use the following markdown table to create an interface for the class below. It should have detailed comments and mention if the input is required.
 *
 * Markdown Tables
 * | Name | Description | Value |
 * |-|-|-|
 * | name | The resource name | string (required) |
 * | location | Resource location. | string (required) |
 * | tags | Resource tags. | Dictionary of tag names and values. SeeTags in templates |
 * | sku | The name and tier of the SKU. | Sku |
 * | properties | Resource properties. | InstancePoolProperties |
 * | Name | Description | Value |
 * |-|-|-|
 * | licenseType | The license type. Possible values are 'LicenseIncluded' (price for SQL license is included) and 'BasePrice' (without SQL license price). | 'BasePrice''LicenseIncluded' (required) |
 * | subnetId | Resource ID of the subnet to place this instance pool in. | string (required) |
 * | vCores | Count of vCores belonging to this instance pool. | int (required) |
 * | Name | Description | Value |
 * |-|-|-|
 * | capacity | Capacity of the particular SKU. | int |
 * | family | If the service has different generations of hardware, for the same SKU, then that can be captured here. | string |
 * | name | The name of the SKU, typically, a letter + Number code, e.g. P3. | string (required) |
 * | size | Size of the particular SKU | string |
 * | tier | The tier or edition of the particular SKU, e.g. Basic, Premium. | string |
 */
