import { Construct } from "constructs";
import { AzAPIBase, IAzAPIBaseProps } from "./core-azapi";

/**
 * Interface representing the properties for instance pool configuration.
 *
 * @extends IAzAPIBaseProps Base properties including name, location, and tags.
 */
export interface CdnProfilesAfdendpointsProps extends IAzAPIBaseProps {
/**
   * In Bicep, you can specify the parent resource for a child resource. You only need to add this property when the child resource is declared outside of the parent resource.For more information, seeChild resource outside parent resource.
   */
readonly parent?: Symbolic name for resource of type:profiles;

/**
   * Indicates the endpoint name reuse scope. The default value is TenantReuse.
   */
readonly autoGeneratedDomainNameLabelScope?: 'NoReuse''ResourceGroupReuse''SubscriptionReuse''TenantReuse';

/**
   * Whether to enable use of this rule. Permitted values are 'Enabled' or 'Disabled'
   */
readonly enabledState?: 'Disabled''Enabled';
}

/**
 * CdnProfilesAfdendpoints resource
 */
export class CdnProfilesAfdendpoints extends AzAPIBase {
  constructor(scope: Construct, id: string, props: CdnProfilesAfdendpointsProps) {
    super(scope, id, props);
  }

  protected getResourceType(): string {
    return "Microsoft.Cdn/profiles/afdEndpoints@2023-07-01-preview";
  }

  protected getResourceBody(props: CdnProfilesAfdendpointsProps): string {
    return JSON.stringify(
        {properties: {autoGeneratedDomainNameLabelScope: "string", enabledState: "string"}}
    );
  }
}
